using System;
namespace NBGCurrency.Configuration
{
    internal enum CurrencyEnumCodes
    {
        AED = 1,
        AMD = 2,
        AUD = 3,
        AZN = 4,
        BGN = 5,
        BYR = 6,
        CAD = 7,
        CHF = 8,
        CNY = 9,
        CZK = 10,
        DKK = 11,
        EEK = 12,
        EGP = 13,
        EUR = 14,
        GBP = 15,
        HKD = 16,
        HUF = 17,
        ILS = 18,
        INR = 19,
        IRR = 20,
        ISK = 21,
        JPY = 22,
        KGS = 23,
        KWD = 24,
        KZT = 25,
        LTL = 26,
        LVL = 27,
        MDL = 28,
        NOK = 29,
        NZD = 30,
        PLN = 31,
        RON = 32,
        RSD = 33,
        RUB = 34,
        SEK = 35,
        SGD = 36,
        TJS = 37,
        TMT = 38,
        TRY = 39,
        UAH = 40,
        USD = 41,
        UZS = 42
    }
}
